## Working with NumPy
NumPy is great at storing and manipulating numerical data in arrays.

## What is Numpy?

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

## What is an array?

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

Let's take a look at an example.

Twice Charred in a fictional (mostly) movie review site where four good friends and movie reviewers, 
Lorie, Marty, Tori, and Kurtz watch movies and give them ratings on a scale of 0 to 100.

In [2]:
import numpy as np

when the gang rates a movie, we can store their ratings in a Numpy array "movie_ratings"

In [3]:
movie_ratings = np.array([63.0, 54.0, 70.0, 50.0])

But they see more than one movie, so we have to create a 2-dimensional array where each row is their ratings for a specific movie.

In [4]:
movie_ratings = np.array([[63.0, 54.0, 70.0, 50.0],
                          [94.0, 85.0, 89.0, 95.0],
                          [64.0, 90.0, 73.0, 85.0]])

Some fans prefer to have the movies rated on a five star scale, so we can use NumPy to easily divide each element by 20.

In [6]:
movie_rating_stars = movie_ratings / 20

In [9]:
movie_rating_stars

array([[3.15, 2.7 , 3.5 , 2.5 ],
       [4.7 , 4.25, 4.45, 4.75],
       [3.2 , 4.5 , 3.65, 4.25]])

Now let's say the ratings are always in the same order (Lorie, Marty, Tori, Kurtz) if we wanted to create an array that only had Tori's ratings, we could select that from our movie_ratings array.

In [12]:
tori_ratings = movie_rating_stars[:,2]
tori_ratings

array([3.5 , 4.45, 3.65])

In [14]:
lorie_ratings = movie_rating_stars[:, :1]
lorie_ratings

array([[3.15],
       [4.7 ],
       [3.2 ]])

Now, say we find that we have very similar taste to Marty, so we only want to see movies that he gives a good rating to, we can use logic to select those movies.

Let's select all of Marty's ratings that are over 80:

In [15]:
martys_ratings = movie_ratings[:,1:2]
martys_ratings[martys_ratings > 80]

array([85., 90.])

## NumPy Arrays
NumPy includes a powerful data structure known as an array. A NumPy array is a special type of list. It’s a data structure that organizes multiple items. Each item can be of any type (strings, numbers, or even other arrays).

Arrays are most powerful when they are used to store numbers. This is because arrays give us special ways of performing mathematical operations that are both simpler to write and more efficient computationally. We’ll get more into this later.

A NumPy array looks a lot like a Python list:

In [17]:
my_list = [1, 2, 3, 4, 5, 6]

In [20]:
my_array = np.array(my_list)

In [21]:
my_array

array([1, 2, 3, 4, 5, 6])

Imagine you’re a teacher and you need to keep track of your student’s test scores. On the first test, the students received the following scores:

92, 94, 88, 91, 87

Create a NumPy array with these values and save it with the name test_1.

In [23]:
test_1 = [92, 94, 88, 91, 87]

In [25]:
test_1 = np.array(test_1)
test_1

array([92, 94, 88, 91, 87])